// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wskymmdpzekipbanpdrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indza3ltbWRwemVraXBiYW5wZHJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjMwODksImV4cCI6MjA2NTQ5OTA4OX0.QNjVTONMTT3ulBT846DajSbhkYzpoSMUkCNUePMjqTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);